language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
    - composer install
    - cd Test/Phpunit
    - composer install
    - vendor/bin/phpunit
    - cd ../codeSniffer
    - phpcs

notifications:
    on_failure: always
    on_change: always
    on_success: never
